---

# Defines Yaml anchor for the stable CI test
molecule-stable: &molecule-stable
  image: lowess/drone-molecule:2.2.3.0
  task: test
  pull: true
  environment:
    - CI_UUID=_stable_${DRONE_COMMIT_SHA:0:8}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - molecule_stable_${DRONE_COMMIT_SHA:0:8}:/tmp

# Defines the Yaml anchor for the preview CI test
molecule-preview: &molecule-preview
  image: lowess/drone-molecule:2.6.3
  task: test
  pull: true
  environment:
    - CI_UUID=_preview_${DRONE_COMMIT_SHA:0:8}
    - ANSIBLE_STRATEGY=mitogen_linear
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - molecule_preview_${DRONE_COMMIT_SHA:0:8}:/tmp

pipeline:
  # CI / CD against current production version
  molecule-stable:
    <<: *molecule-stable
    group: molecule

  # CI / CD against the preview version
  molecule-preview:
    <<: *molecule-preview
    group: molecule
